<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UseCases\Commands\NewFolder\**" />
    <EmbeddedResource Remove="UseCases\Commands\NewFolder\**" />
    <None Remove="UseCases\Commands\NewFolder\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PatternNET.Domain\PatternNET.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Results\" />
    <Folder Include="UseCases\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
